### ISSUE TITLE
Using one svg icon for several fasteners.

### ISSUE THREAD

**Issue by FreeCAD-Tools** [shaise/FreeCAD_FastenersWB#204]
Now when a developer adds a new fastener, he has to create a new svg icon.
I think that for several fastener is better way to use one svg icon, for example: din 96, gost 1144-1, gost 1144-2.
May add а fourth optional parameter to the command table? like:

    "DIN96":   (translate("FastenerCmd", "DIN 96 Slotted half round head wood screw"), SlottedGroup,\
                      ScrewParametersLC, "SlottedHRWoodScrew.svg"),

So far, this is at the level of an idea. At code, I do not know how to do it.
Does anyone have any idea?

**Comment by alexneufeld** [comment]
Having a separate icon for each fastener is the simpler solution IMO. svg files are cheap,  and if the user decides to use their own custom icons (which is already a possibility in FreeCAD, and will likely become more common as the preference pack system becomes more robust), they would probably not like it if some icons were not individually changeable because of an ad-hoc de-duplication system in this workbench.
