### ISSUE TITLE
DIN 1624 is wrongly named

### ISSUE THREAD

**Issue by tobiasfalk** [shaise/FreeCAD_FastenersWB#320]
[DIN 1624](https://www.beuth.de/en/standard/din-1624/1349780) is something completely different(Steel flat products; cold reduced mild unalloyed steel strip in widths not exceeding 650 mm; technical delivery conditions).
It is also not [ISO 1624](https://www.beuth.de/en/standard/iso-1624/50214523).
I was not able to find a corresponding standard for it, but I think it should be renamed.
I also saw that if one searches DIN 1624 results for this appear, but not many.

**Comment by tobiasfalk** [comment]
I just realized that it is in FSDatata and [FastenersCmd.py](https://github.com/shaise/FreeCAD_FastenersWB/blob/a0810d5311dac34413cd2c60158c23e4c3cf5bbf/FastenersCmd.py#L176) but not available in FreeCAD

**Comment by alexneufeld** [comment]
You are likely correct that these T-nuts aren't actually specified by the DIN 1624 standard.
Several manufacturers do list them as such, however (which is why I initially labeled them this way):
- https://fullerfasteners.com/products/din-1624-t-nut-bare-with-4-prongs/
- https://www.singhaniainternational.com/products-details/T-Nut_-Four_Prong_Tee-Nut-_DIN_1624/105
- https://www.xinchi-industry.com/din-1624/

Most likely the steel stock they are made from conforms to the *actual* DIN 1624 standard?? This seems to be an annoying case where common industry practice is nonsense, and there's no actual standard to follow. Very annoying for a simple and reasonably commonly used fastener...

**Comment by tobiasfalk** [comment]
We already have non standard parts that have a descriptive name, so doing the same here sounds reasonable.
Somthing on the line of "4 prong wood thread insert".
While doing that I would suggest moving it in to the Insert category, because if I am right these are used for wood as inserts.

**Comment by alexneufeld** [comment]
sounds good to me :+1:
